projConfig.toml for xlnode_py

[meta]
    version = '0.1.0'

[project]
    name = 'xlnode_py'  # distro name
    package = 'xlnode_py'  # internal name
    proj_dir = '/home/jdd/dev/py/xlnode_py'
    main_lang = 'py'
    version = '0.0.8'
    version_date = '2017-10-15'
    author = 'Jim Dixon'
    author_email = 'jddixon@gmail.com'
    copyright = '2017'
    description = 'nodeid layer for xlattice_py'
    dev_status = 'pre_alpha'
    license = 'mit'
    state = 'shared'
    url = 'https://jddixon.github.io/xlnode_py'

[py]
    packages=['xlnode']
    package_dir = ['src']
    test_dir = ['tests']
    py_modules=[]
    scripts=[]
    ext_modules=[]

    # sdReq output
    distshare=['rnglib']
    env_vars=[]
    requirements=['setuptools']
    test_requirements=[]
