[meta]
version = "0.1.0"

[project]
name = "xlnode_py"
package = "xlnode_py"
main_lang = "py"
version = "0.1.0"
version_date = "2018-01-11"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
copyright = "2017"
description = "nodeid layer for xlattice_py"
dev_status = "pre_alpha"
license = "mit"
relpath = "py/xlnode_py"
state = "shared"
url = "https://jddixon.github.io/xlnode_py"

[py]
packages = [ "xlnode",]
package_dir = [ "src",]
test_dir = [ "tests",]
py_modules = []
scripts = []
ext_modules = []
distshare = [ "rnglib",]
env_vars = []
requirements = [ "setuptools",]
test_requirements = []
